main_page_link = "http://selenium1py.pythonanywhere.com"
search_input = "input#id_q"
search_submit = "input.btn.btn-default"
search_title = "div.page-header h1"
search_result = "article.product_pod"
button_language_go = "button.btn.btn-default[type='submit']"
menu_products = "a.dropdown-toggle"
button_basket = "span.btn-group a.btn.btn-default"
login_link = "a#login_link"
email_sign_up = "input[name='registration-email']"
password_sign_up = "input[name='registration-password1']"
submit_pass_sign_up = "input[name='registration-password2']"
submit_sign_up_button = "button[name='registration_submit']"
welcome_text_sign_up = "div.alertinner.wicon"
email_sign_in = "input[name='login-username']"
password_sign_in = "input[name='login-password']"
submit_sign_in_button = "button[name='login_submit']"
welcome_text_sign_in = "div.alertinner.wicon"
button_add = "button[type='submit'].btn.btn-lg.btn-primary.btn-add-to-basket"
add_item_notification = "div#messages >div.alert:nth-child(1)>.alertinner"
item_in_basket = "div.row h3 a"
item_quantity = "input[type='number']#id_form-0-quantity"
button_update_quantity = "span.input-group-btn button.btn.btn-default[type='submit']"
basket_note_change = "div.alertinner p:nth-child(1)"
offers_button = "ul.dropdown-menu li:nth-child(6)"
page_title = "div.page-header.action h1"
page_subtitle1 = "div#content_inner h2:nth-child(1)"
main_page_subtitle = "section.well.well-blank div.sub-header h2"
main_page_subtitle2 = "article.well.promotion_single div.sub-header h2"
main_page_subtitle3 = "section.well.well-blank div.sub-header h3"
item_page_title = "h1"
button_add_search = "button.btn.btn-primary.btn-block"



all_products = "//a[contains(text(),'All products')]"
first_item = "//a[contains(text(),'The shellcoder'\s handbook')]"
